name: Deploy server to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}" > .env
          echo "BUNNY_ACCESS_KEY=${{ secrets.BUNNY_ACCESS_KEY }}" >> .env
          echo "BUNNY_BASE_HOSTNAME=${{ secrets.BUNNY_BASE_HOSTNAME }}" >> .env
          echo "BUNNY_STORAGE_NAME=${{ secrets.BUNNY_STORAGE_NAME }}" >> .env
          echo "BUNNY_FTP_USER=${{ secrets.BUNNY_FTP_USER }}" >> .env
          echo "BUNNY_FTP_PASS=${{ secrets.BUNNY_FTP_PASS }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env

      - name: Copy server directory to VPS
        uses: appleboy/scp-action@master

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "server/*"
          target: "${{ secrets.SERVER_PATH }}/"
          overwrite: true
          debug: true

      - name: Execute deployment script
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            docker stop ${{ secrets.CONTAINER_NAME }} || true
            docker rm ${{ secrets.CONTAINER_NAME }} || true
            docker build -t ${{ secrets.CONTAINER_NAME }} .
            docker run -d --name ${{ secrets.CONTAINER_NAME }} -p ${{ secrets.ORIGIN }}:${{ secrets.ORIGIN }} ${{ secrets.CONTAINER_NAME }}
